const localStyles = {
  titleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 16,
  },
  accountBadge: {
    background: "#f8faf9",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
    color: "#5f6f66",
    fontSize: 13,
    fontWeight: 800,
    padding: "6px 9px",
  },
  alert: {
    border: "1px solid #cfd8d3",
    background: "#f8faf9",
    borderRadius: 4,
    color: "#10201a",
    fontSize: 14,
    fontWeight: 700,
    marginBottom: 16,
    padding: "11px 12px",
  },
  alertError: {
    background: "#fdebea",
    borderColor: "#f2b8b5",
    color: "#b42318",
  },
  alertSuccess: {
    background: "#e6f4ed",
    borderColor: "#b7dfc4",
    color: "#146c43",
  },
  alertWarning: {
    background: "#fff8e5",
    borderColor: "#ead08a",
    color: "#735c0f",
  },
  deductionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 8,
    marginTop: 12,
    fontSize: 13,
  },
  mainTabsWrapper: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
    gap: 8,
    marginBottom: 16,
  },
  mainTabBtn: {
    border: "1px solid #cfd8d3",
    background: "#ffffff",
    borderRadius: 4,
    padding: "10px 12px",
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "left",
  },
  mainTabBtnActive: {
    background: "#eef7fb",
    color: "#174a6b",
    borderColor: "#1f5f8b",
  },
  segmentWrapper: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 16,
  },
  segmentBtn: {
    border: "none",
    borderRight: "1px solid #cfd8d3",
    background: "#ffffff",
    padding: "10px 12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  segmentBtnActive: {
    background: "#eef7fb",
    color: "#174a6b",
  },
  subTabsWrapper: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginTop: 18,
    marginBottom: 14,
  },
  subTabBtn: {
    border: "1px solid #cfd8d3",
    background: "#ffffff",
    borderRadius: 4,
    padding: "10px 12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  subTabBtnActive: {
    background: "#eef7fb",
    borderColor: "#1f5f8b",
    color: "#174a6b",
  },
  formActions: {
    marginTop: 20,
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: 10,
    alignItems: "center",
  },
  cancelBtn: {
    background: "#ffffff",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
    color: "#5f6f66",
    fontWeight: 700,
    cursor: "pointer",
    padding: "10px 14px",
  },
  undoCard: {
    marginTop: 20,
    padding: 14,
    background: "#fff8e5",
    border: "1px solid #ead08a",
    borderRadius: 4,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  undoBtn: {
    background: "none",
    border: "none",
    color: "#174a6b",
    fontWeight: 800,
    cursor: "pointer",
  },
  editBtn: {
    background: "#ffffff",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
    color: "#174a6b",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer",
    padding: "4px 7px",
  },
  previewText: {
    marginTop: -4,
    marginBottom: 12,
    fontSize: 12,
    color: "#5f6f66",
  },
  rowActions: {
    marginTop: 6,
    display: "flex",
    gap: 10,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  userBadge: {
    background: "#f8faf9",
    color: "#5f6f66",
    border: "1px solid #cfd8d3",
    padding: "2px 6px",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 700,
  },
  totalCard: {
    marginTop: 20,
    padding: 16,
    background: "#ffffff",
    border: "1px solid #cfd8d3",
    borderRadius: 6,
    marginBottom: 18,
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    fontWeight: 800,
    marginBottom: 10,
  },
  progressBarWrapper: {
    height: 8,
    background: "#e4ebe7",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    transition: "width 0.2s ease",
  },
  percentText: {
    marginTop: 8,
    fontSize: 13,
    color: "#5f6f66",
  },
  breakdownRow: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 10,
    fontSize: 14,
    fontWeight: 700,
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    color: "#10201a",
    fontWeight: 700,
  },
  fieldGroup: {
    display: "grid",
    gap: 6,
    marginBottom: 12,
  },
  fieldLabel: {
    color: "#10201a",
    fontSize: 13,
    fontWeight: 800,
  },
  fieldHint: {
    color: "#5f6f66",
    fontSize: 12,
  },
  autoTableWrap: {
    marginTop: 22,
    overflowX: "auto",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
  },
  autoTotalsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    borderBottom: "1px solid #cfd8d3",
    background: "#f8faf9",
  },
  autoTotalItem: {
    display: "grid",
    gap: 4,
    padding: "10px 12px",
  },
  autoTable: {
    width: "100%",
    minWidth: 720,
    borderCollapse: "collapse",
    fontSize: 14,
  },
  emptyTableCell: {
    padding: 18,
    textAlign: "center",
    color: "#5f6f66",
  },
  tableHeaderCell: {
    padding: "11px 10px",
    textAlign: "left",
    background: "#f8faf9",
    borderBottom: "1px solid #cfd8d3",
    color: "#10201a",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  tableCell: {
    padding: "11px 10px",
    borderBottom: "1px solid #e4ebe7",
    verticalAlign: "middle",
  },
  tableActionGroup: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    background: "#f8faf9",
    borderRadius: 4,
    marginTop: 8,
    padding: "12px 10px",
  },
  exportActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 16,
  },
  secondaryButton: {
    background: "#ffffff",
    color: "#174a6b",
    border: "1px solid #cfd8d3",
    borderRadius: 4,
    padding: "10px 14px",
    fontWeight: 700,
    cursor: "pointer",
  },
};

export default localStyles;
