const baseFont = "'Segoe UI', Arial, sans-serif";

const colors = {
  page: "var(--app-page)",
  panel: "var(--app-panel)",
  panelAlt: "var(--app-panel-alt)",
  border: "var(--app-border)",
  borderSoft: "var(--app-border-soft)",
  text: "var(--app-text)",
  muted: "var(--app-muted)",
  primary: "var(--app-primary)",
  primaryDark: "var(--app-primary-dark)",
  primarySoft: "var(--app-primary-soft)",
  success: "var(--app-success)",
  danger: "var(--app-danger)",
  dangerSoft: "var(--app-danger-soft)",
  successSoft: "#e6f4ed",
};

const buttonBase = {
  border: "1px solid transparent",
  borderRadius: 4,
  padding: "10px 14px",
  fontWeight: 700,
  fontSize: 15,
  cursor: "pointer",
};

const inputBase = {
  width: "100%",
  padding: "10px 12px",
  borderRadius: 4,
  border: `1px solid ${colors.border}`,
  marginBottom: 12,
  fontSize: 15,
  background: colors.panel,
  color: colors.text,
  boxSizing: "border-box",
};

const styles = {
  container: {
    width: "100%",
    maxWidth: 1040,
    margin: "0 auto",
    padding: "24px",
    fontFamily: baseFont,
    color: colors.text,
    minHeight: "100%",
  },
  centerContainer: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: colors.page,
    padding: 20,
    fontFamily: baseFont,
    color: colors.text,
  },
  centerCard: {
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    borderTop: `4px solid ${colors.primary}`,
    borderRadius: 6,
    padding: 28,
    width: "100%",
    maxWidth: 420,
    textAlign: "left",
  },
  title: {
    fontSize: 24,
    lineHeight: 1.2,
    fontWeight: 800,
    margin: "0 0 18px",
    color: colors.text,
  },
  heroCard: {
    background: colors.panel,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderLeft: `5px solid ${colors.primary}`,
    borderRadius: 6,
    padding: 18,
    marginBottom: 20,
  },
  heroLabel: {
    fontSize: 14,
    color: colors.muted,
    marginBottom: 6,
  },
  heroValue: {
    fontSize: 30,
    fontWeight: 800,
    marginTop: 4,
    color: colors.text,
  },
  card: {
    background: colors.panel,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: 18,
    marginBottom: 18,
  },
  sectionTitle: {
    margin: "0 0 14px",
    fontWeight: 800,
    fontSize: 18,
    color: colors.text,
  },
  input: inputBase,
  blueButton: {
    ...buttonBase,
    width: "100%",
    background: colors.primary,
    color: "#ffffff",
  },
  greenButton: {
    ...buttonBase,
    width: "100%",
    background: colors.success,
    color: "#ffffff",
  },
  authIcon: { display: "none" },
  authTitle: {
    fontSize: 22,
    fontWeight: 800,
    margin: "0 0 18px",
  },
  authSubtitle: {
    fontSize: 14,
    color: colors.muted,
    lineHeight: 1.5,
    marginBottom: 20,
  },
  authInput: inputBase,
  primaryButton: {
    ...buttonBase,
    width: "100%",
    background: colors.primary,
    color: "#ffffff",
    marginTop: 6,
  },
  messageBox: {
    marginTop: 14,
    padding: 12,
    borderRadius: 4,
    fontSize: 14,
    border: `1px solid ${colors.borderSoft}`,
  },
  errorBox: {
    marginTop: 12,
    marginBottom: 10,
    padding: 12,
    borderRadius: 4,
    background: colors.dangerSoft,
    color: colors.danger,
    border: "1px solid #f2b8b5",
    fontSize: 14,
  },
  separator: {
    height: 1,
    background: colors.borderSoft,
    margin: "20px 0",
  },
  secondaryButton: {
    ...buttonBase,
    width: "100%",
    background: colors.panelAlt,
    color: colors.text,
    borderColor: colors.border,
    marginBottom: 10,
  },
  linkButton: {
    background: "transparent",
    border: "none",
    color: colors.primary,
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
    marginBottom: 10,
  },
  backButton: {
    background: "transparent",
    border: "none",
    color: colors.muted,
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
  },
  bottomActions: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    fontSize: 14,
  },
  linkBlue: {
    background: "transparent",
    border: "none",
    color: colors.primary,
    cursor: "pointer",
    padding: 0,
  },
  linkGray: {
    background: "transparent",
    border: "none",
    color: colors.muted,
    cursor: "pointer",
    padding: 0,
  },
  homeHeroIcon: { display: "none" },
  homeSubtitle: {
    fontSize: 15,
    color: colors.muted,
    lineHeight: 1.5,
    marginBottom: 20,
  },
  homeFooter: {
    fontSize: 13,
    color: colors.muted,
    marginBottom: 22,
  },
  installAction: {
    display: "flex",
    justifyContent: "center",
    marginTop: 14,
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    padding: "12px 0",
    borderBottom: `1px solid ${colors.borderSoft}`,
    cursor: "pointer",
  },
  activeRow: {
    background: colors.primarySoft,
    borderRadius: 4,
    padding: 12,
  },
  selectedCard: {
    background: colors.panelAlt,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: 4,
    padding: 12,
    marginBottom: 18,
  },
  selectedLabel: {
    fontSize: 13,
    color: colors.muted,
  },
  selectedValue: {
    fontSize: 16,
    fontWeight: 800,
    marginTop: 4,
  },
  amount: {
    fontWeight: 800,
    fontSize: 16,
  },
  date: {
    fontSize: 13,
    color: colors.muted,
  },
  updated: {
    fontSize: 12,
    color: colors.muted,
  },
  deleteBtn: {
    border: "1px solid #f2b8b5",
    background: "#ffffff",
    borderRadius: 4,
    fontSize: 12,
    color: colors.danger,
    fontWeight: 700,
    cursor: "pointer",
    padding: "4px 7px",
  },
  message: {
    marginBottom: 14,
    fontWeight: 700,
    color: colors.muted,
  },
};

export default styles;
