"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = BASE_DIR.parent


def env_list(name, default=None):
    """Return a comma-separated environment variable as a clean list."""
    value = os.environ.get(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-c&=!4yxoavqa!yumj010%u-zv$3aze^^-onmasywn$cwgt29)z",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

# Backend-ul poate fi apelat fie pe acelasi origin ca frontend-ul, fie pe portul
# 8000 ca fallback. In DEBUG acceptam hosturi dinamice de dev/LAN pentru ca IP-ul
# masinii se poate schimba; in productie seteaza explicit DJANGO_ALLOWED_HOSTS.
DEFAULT_ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    "192.168.2.102",
    "100.75.19.22",
    ".ts.net",
]

ALLOW_ALL_HOSTS = env_bool(
    "DJANGO_ALLOW_ALL_HOSTS",
    DEBUG and os.environ.get("DJANGO_ALLOWED_HOSTS") is None,
)

ALLOWED_HOSTS = (
    ["*"]
    if ALLOW_ALL_HOSTS
    else env_list("DJANGO_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)
)

DEFAULT_FRONTEND_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.2.102:5173",
    "http://192.168.2.102:8080",
    "http://100.75.19.22:5173",
    "http://100.75.19.22:8080",
    "https://localhost:5173",
    "https://127.0.0.1:5173",
    "https://localhost:8080",
    "https://127.0.0.1:8080",
    "https://192.168.2.102:5173",
    "https://192.168.2.102:8080",
    "https://100.75.19.22:5173",
    "https://100.75.19.22:8080",
]

FRONTEND_ORIGINS = env_list(
    "DJANGO_FRONTEND_ORIGINS",
    env_list("DJANGO_CORS_ALLOWED_ORIGINS", DEFAULT_FRONTEND_ORIGINS),
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "finante",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("POSTGRES_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("POSTGRES_DB", "buget_db"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Arhivele financiare sunt private și se descarcă numai prin endpointuri
# autentificate. Nu muta acest director sub MEDIA_ROOT sau într-un alias nginx.
FINANCIAL_ARCHIVE_ROOT = Path(
    os.environ.get(
        "FINANCIAL_ARCHIVE_ROOT",
        REPO_DIR / "arhiva" / "date-financiare",
    )
).resolve()
FINANCIAL_ARCHIVE_KEEP_CYCLES = max(
    2,
    env_int("FINANCIAL_ARCHIVE_KEEP_CYCLES", 2),
)

FRONTEND_DIST_DIR = REPO_DIR / "frontend" / "dist"
STATICFILES_DIRS = [FRONTEND_DIST_DIR] if FRONTEND_DIST_DIR.exists() else []

DEFAULT_CORS_ALLOW_ALL_ORIGINS = (
    DEBUG
    and os.environ.get("DJANGO_FRONTEND_ORIGINS") is None
    and os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS") is None
)

CORS_ALLOW_ALL_ORIGINS = env_bool(
    "DJANGO_CORS_ALLOW_ALL_ORIGINS",
    DEFAULT_CORS_ALLOW_ALL_ORIGINS,
)
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
CORS_ALLOWED_ORIGIN_REGEXES = env_list(
    "DJANGO_CORS_ALLOWED_ORIGIN_REGEXES",
    [r"^https?://[A-Za-z0-9.-]+\.ts\.net(?::(5173|8080))?$"],
)
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS + env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    env_list(
        "DJANGO_CSRF_TRUSTED_ORIGIN_PATTERNS",
        ["http://*.ts.net", "https://*.ts.net"],
    ),
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=env_int("JWT_ACCESS_TOKEN_MINUTES", 60)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env_int("JWT_REFRESH_TOKEN_DAYS", 30)),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in {
    "1",
    "true",
    "yes",
    "on",
}
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "emailul_tau@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "app_password")
