server {
    listen 8080;
    server_name 192.168.2.102 100.75.19.22 localhost;

    client_max_body_size 8M;

    root /home/c0stelus/aplicatie_server/frontend/dist;
    index index.html;

    location /api/ {
        proxy_pass http://unix:/home/c0stelus/aplicatie_server/backend/gunicorn.sock;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /media/ {
        alias /home/c0stelus/aplicatie_server/backend/media/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
