# Generated by Django 6.0.2 on 2026-02-13 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheltuialaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.CharField(max_length=100)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Lei')], max_length=3)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheltuieli_fixe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='CheltuialaVariabila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('alimente', 'Alimente'), ('sanatate', 'Sănătate'), ('auto', 'Auto'), ('cultura', 'Cultură'), ('shopping', 'Shopping'), ('neprevazute', 'Neprevăzute'), ('economii', 'Economii'), ('vacanta', 'Vacanță'), ('animalute', 'Animăluțe'), ('divertisment', 'Divertisment'), ('investitii', 'Investiții'), ('vacanta_cheltuita', 'Vacanță Cheltuită')], max_length=20)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Lei')], max_length=3)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheltuieli_variabile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='EconomieVacanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('economii', 'Economii'), ('cheltuieli', 'Cheltuieli')], max_length=15)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Lei')], max_length=3)),
                ('data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economii_vacanta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Fond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suma_ron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observatii', models.TextField(blank=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonduri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MiscareFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('adauga', 'Adauga'), ('retrage', 'Retrage')], max_length=10)),
                ('suma_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suma_ron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observatii', models.TextField(blank=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscari_fonduri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UserBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bridges', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bridges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Lei')], max_length=3)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venituri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EconomieLunara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luna', models.CharField(max_length=7)),
                ('sold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economii_lunare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['luna'],
                'unique_together': {('user', 'luna')},
            },
        ),
    ]
