# Generated by Django 6.0.2 on 2026-05-18 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finante', '0002_miscarefond_rubrica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venit',
            name='sursa',
            field=models.CharField(blank=True, default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('EUR', 'Euro'), ('RON', 'Lei')], default='RON', max_length=3)),
                ('activ', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['zi', 'id'],
            },
        ),
        migrations.AddField(
            model_name='venit',
            name='salary_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venituri_generate', to='finante.salaryschedule'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.TextField(blank=True, default='')),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('ocupatia', models.CharField(blank=True, default='', max_length=120)),
                ('venit_estimat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('venit_estimat_lunar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealizariTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luna', models.CharField(max_length=7)),
                ('fixed_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category_targets', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizari_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-luna'],
                'unique_together': {('user', 'luna')},
            },
        ),
    ]
