# Generated by Codex on 2026-06-11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finante", "0003_venit_sursa_emailchangerequest_salaryschedule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheltuialaFixaAutomata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denumire", models.CharField(max_length=100)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "cursivitate",
                    models.CharField(
                        choices=[
                            ("lunar", "O data pe luna"),
                            ("de_doua_ori_luna", "De 2 ori pe luna"),
                            ("de_trei_ori_luna", "De 3 ori pe luna"),
                            ("la_2_luni", "O data la 2 luni"),
                            ("la_3_luni", "O data la 3 luni"),
                            ("la_6_luni", "O data la 6 luni"),
                            ("anual", "O data pe an"),
                        ],
                        default="lunar",
                        max_length=30,
                    ),
                ),
                ("suma", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("RON", "Lei")],
                        max_length=3,
                    ),
                ),
                ("activ", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheltuieli_fixe_automate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["data", "id"],
            },
        ),
        migrations.AddField(
            model_name="cheltuialafixa",
            name="sursa",
            field=models.CharField(blank=True, default="manual", max_length=30),
        ),
        migrations.AddField(
            model_name="cheltuialafixa",
            name="automatizare",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cheltuieli_generate",
                to="finante.cheltuialafixaautomata",
            ),
        ),
    ]
