# Generated by Django 6.0.2 on 2026-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finante', '0003_realizarelunara'),
        ('finante', '0006_profile_salary_details'),
    ]

    operations = [
    ]
