# Generated by Django 6.0.2 on 2026-06-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finante', '0007_merge_20260612_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealizareLunara',
        ),
    ]
