# Generated by Django 6.0.2 on 2026-06-13 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finante', '0009_credit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscarefond',
            name='data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='miscarefond',
            name='rubrica',
            field=models.CharField(default='alte_investitii', max_length=60),
        ),
        migrations.CreateModel(
            name='InvestitieAutomata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(blank=True, default='', max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('rubrica', models.CharField(default='alte_investitii', max_length=60)),
                ('suma_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suma_ron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investitii_automate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data', 'id'],
            },
        ),
        migrations.AddField(
            model_name='miscarefond',
            name='automatizare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miscari_generate', to='finante.investitieautomata'),
        ),
        migrations.CreateModel(
            name='InvestitieCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorii_investitii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'id'],
                'unique_together': {('user', 'value')},
            },
        ),
    ]
